resources:
  containers:
    - container: rocky8-builder
      image: levelsbeyond-docker.jfrog.io/rocky8-java-8-and-11-builder:3.0.0
      endpoint: LB_Docker_Images
      env:
        JAVA8_HOME: /usr/lib/jvm/java-1.8.0
        JAVA11_HOME: /usr/lib/jvm/java-11
        JAVA_OPTS: "-Xmx5g -Xms5g"

variables:
  performNpmAuthenticate: false
  dynamicVersion: true
  # system.debug: true

pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - '*'

stages:
  - stage: Publish
    jobs:
      - job: NpmSteps
        container: rocky8-builder
        steps:
          - task: DownloadSecureFile@1
            name: DownloadNpmrcFile
            inputs:
              secureFile: '.npmrc'
          - task: Bash@3
            name: GeneralBash
            displayName: 'Configure npm'
            inputs:
              targetType: 'inline'
              script: |
                # output npm info
                echo "============= start of debug info ============="
                echo "pwd ==> $(pwd)"
                echo "Agent.TempDirectory ==> $(Agent.TempDirectory)"
                ls -lah $(Agent.TempDirectory)
                echo "System.DefaultWorkingDirectory ==> $(System.DefaultWorkingDirectory)"
                ls -lah ${SYSTEM_DEFAULTWORKINGDIRECTORY}
                echo "get npm and node info"
                npm --version
                node -v
                echo "npm config file: $(DownloadNpmrcFile.secureFilePath)"
                echo "============= start of npm config file contents ============="
                cat $(DownloadNpmrcFile.secureFilePath)
                echo "============== end of npm config file contents =============="
                whoamistr=$(npm whoami --userconfig $(DownloadNpmrcFile.secureFilePath))
                echo "whoami specifying npm userconfig file return: $?"
                echo "============= start of whoami cmd output ============="
                firstPartWhoami=${whoamistr::-2}
                secondPartWhoami=${whoamistr: -2}
                echo "whoamistr: ${whoamistr}"
                echo "firstPartWhoami: ${firstPartWhoami}"
                echo "secondPartWhoami: ${secondPartWhoami}"
                echo "firstPartWhoami-secondPartWhoami: ${firstPartWhoami}-${secondPartWhoami}"
                echo "============== end of whoami cmd output =============="
                echo "============== end of debug info =============="
          - task: npmAuthenticate@0
            condition: ${{variables.performNpmAuthenticate}}
            inputs:
              workingFile: $(System.DefaultWorkingDirectory)/.npmrc
              customEndpoint: "Artifactory NPM"
          - task: Bash@3
            name: NpmPublish
            displayName: 'npm_publish'
            inputs:
              targetType: 'inline'
              script: |
                echo "============= start of debug info ============="
                echo "System.DefaultWorkingDirectory ==> $(System.DefaultWorkingDirectory)"
                ls -lah ${SYSTEM_DEFAULTWORKINGDIRECTORY}
                echo "output the npm config info"
                npm config list -l
                echo "run generate.sh script"
                ./generate.sh ${{variables.dynamicVersion}} $(DownloadNpmrcFile.secureFilePath)
                echo "============= end of debug info ============="
          - task: Bash@3
            name: NpmWhoAmI
            displayName: 'npm_whoami'
            inputs:
              targetType: 'inline'
              script: |
                echo "============= start of debug info ============="
                echo "System.DefaultWorkingDirectory ==> $(System.DefaultWorkingDirectory)"
                ls -lah ${SYSTEM_DEFAULTWORKINGDIRECTORY}
                echo "npm config file: $(System.DefaultWorkingDirectory)/.npmrc"
                echo "============= start of npm config file contents ============="
                cat $(System.DefaultWorkingDirectory)/.npmrc
                echo "============== end of npm config file contents =============="
                whoamistr=$(npm whoami --userconfig $(System.DefaultWorkingDirectory)/.npmrc)
                echo "whoami specifying npm userconfig file return: $?"
                echo "============= start of whoami cmd output ============="
                firstPartWhoami=${whoamistr::-2}
                secondPartWhoami=${whoamistr: -2}
                echo "whoamistr: ${whoamistr}"
                echo "firstPartWhoami: ${firstPartWhoami}"
                echo "secondPartWhoami: ${secondPartWhoami}"
                echo "firstPartWhoami-secondPartWhoami: ${firstPartWhoami}-${secondPartWhoami}"
                echo "============== end of whoami cmd output =============="
                whoamistr=$(npm whoami)
                echo "whoami without specifying npm userconfig file return: $?"
                echo "============= start of whoami cmd output ============="
                firstPartWhoami=${whoamistr::-2}
                secondPartWhoami=${whoamistr: -2}
                echo "whoamistr: ${whoamistr}"
                echo "firstPartWhoami: ${firstPartWhoami}"
                echo "secondPartWhoami: ${secondPartWhoami}"
                echo "firstPartWhoami-secondPartWhoami: ${firstPartWhoami}-${secondPartWhoami}"
                echo "============== end of whoami cmd output =============="
                echo "============== end of debug info =============="
